from datetime import datetime, timezone

from app.reports.models import BirdsEyeReport


def render_markdown(report: BirdsEyeReport) -> str:
    """Render a BirdsEyeReport to markdown format."""
    sections = []

    # Header
    sections.append("OpenShell Triage — Bird's Eye View")
    sections.append(f"Period: {report.summary.period_label}")
    sections.append("")

    # Summary
    sections.append("SUMMARY")
    sections.append(f"  {report.summary.new_this_period} new issues")

    urgency_parts = []
    for urgency in ["critical", "high", "medium", "low"]:
        count = report.summary.by_urgency.get(urgency, 0)
        urgency_parts.append(f"{count} {urgency}")
    sections.append(f"  {' | '.join(urgency_parts)}")
    sections.append("")

    # Narrative
    sections.append(f'  "{report.narrative}"')
    sections.append("  — generated by Sonnet from the report data")
    sections.append("")

    # Critical & High Issues
    if report.critical_list:
        sections.append("CRITICAL & HIGH ISSUES")
        sections.append(
            "  #     | Issue                                        | Team      | Days Open"
        )
        for issue in report.critical_list:
            days_open = _compute_days_open(issue.assessed_at)
            # Truncate title to 44 chars for alignment
            title = (
                issue.issue_title[:44]
                if len(issue.issue_title) > 44
                else issue.issue_title
            )
            # Truncate team to 9 chars
            team = (
                issue.primary_team[:9]
                if len(issue.primary_team) > 9
                else issue.primary_team
            )
            sections.append(
                f"  {issue.issue_number:<5} | {title:<44} | {team:<9} | {days_open}"
            )
        sections.append("")

    # Team Breakdown
    if report.team_breakdown:
        sections.append("TEAM BREAKDOWN")
        sections.append("  Team          | Total | Crit | High | Med | Low | Trend")
        for team_id in sorted(report.team_breakdown.keys()):
            team = report.team_breakdown[team_id]
            sections.append(
                f"  {team.team_id:<13} | {team.total:<5} | "
                f"{team.by_urgency.get('critical', 0):<4} | "
                f"{team.by_urgency.get('high', 0):<4} | "
                f"{team.by_urgency.get('medium', 0):<3} | "
                f"{team.by_urgency.get('low', 0):<3} | "
                f"{team.trend}"
            )
        sections.append("")

    # Area Heatmap
    if report.area_heatmap:
        sections.append("AREA HEATMAP")
        for area_id in sorted(report.area_heatmap.keys()):
            area = report.area_heatmap[area_id]
            sections.append(
                f"  {area.area}   | {area.current_count} this week (was {area.previous_count}) — {area.trend}"
            )
        sections.append("")

    # Potential Duplicates
    if report.duplicate_clusters:
        sections.append("POTENTIAL DUPLICATES")
        for i, cluster in enumerate(report.duplicate_clusters, start=1):
            sections.append(
                f"  Cluster {i} — {cluster.area} ({cluster.similarity_reason})"
            )
            for issue in cluster.issues:
                sections.append(
                    f"    #{issue.issue_number} {issue.issue_title} — {issue.primary_team}"
                )
        sections.append("")

    # No Red Hat Team
    if report.no_team_list:
        sections.append(f"NO RED HAT TEAM ({len(report.no_team_list)} issues)")
        for issue in report.no_team_list:
            sections.append(f"  #{issue.issue_number} {issue.issue_title}")
        sections.append("")

    return "\n".join(sections)


def _compute_days_open(assessed_at: str) -> str:
    """Compute days between assessed_at and now."""
    try:
        assessed_time = datetime.fromisoformat(assessed_at.replace("Z", "+00:00"))
        now = datetime.now(timezone.utc)
        delta = now - assessed_time
        return str(delta.days)
    except (ValueError, AttributeError):
        return "?"
