apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-issue-triage

resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - cronjob-triage.yaml
