apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: triage-dashboard
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: triage-dashboard
    weight: 100
  port:
    targetPort: http
